development:
  secret_key_base: 'devdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdevdev'

test:
  secret_key_base: 'testtesttesttesttesttesttesttesttesttesttesttesttesttest'

production:
  secret_key_base: ENV['RAILS_SECRET_TOKEN']
